### PR TITLE
Fix `backgroundColor` not being applied correctly to TextInput

### LINKED ISSUE #415: Cannot apply background color to TextInput
### Environment

npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.44 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - ~/.volta/tools/image/node/14.2.0/6.14.4/bin/node
    Yarn: 1.22.0 - ~/.volta/tools/image/yarn/1.22.0/bin/yarn
    npm: 6.14.4 - ~/.volta/tools/image/node/14.2.0/6.14.4/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.0
      System Images: android-28 | Google Play Intel x86 Atom, android-R | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
### Steps to Reproduce
Try to set background on <TextInput> component, component will still have white background in the app

1. <TextInput style={{backgroundColor: 'red}}/>

### PR DESCRIPTION
**Pull request by tido64**
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [x] I am making a fix / change for the macOS implementation of react-native
- [ ] I am making a change required for Microsoft usage of react-native

## Summary

Fixes `backgroundColor` not being applied correctly to `TextInput` (single-line).

Resolves #415

## Changelog

[macOS] [Fixed] - Fix `backgroundColor` not being applied correctly to TextInput

## Test Plan

| Before | After |
| :----: | :---: |
| image | image |

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-macos/pull/443)

### CODE REVIEW

File: Libraries/Text/TextInput/Singleline/RCTUITextField.m [hunk 1]
```diff
@@ -108,6 +108,7 @@ - (instancetype)initWithFrame:(CGRect)frame
 #if TARGET_OS_OSX // [TODO(macOS ISS#2323203)
     self.bordered = NO;
     self.accessibilityRole = NSAccessibilityTextFieldRole;
+    self.backgroundColor = [NSColor clearColor];
```
Comment (tom-un) [inline Libraries/Text/TextInput/Singleline/RCTUITextField.m:111]: Does RCTUITextView.m for multi-line TextInputs just work when `backgroundColor` is set?

Comment (tido64) [reply Libraries/Text/TextInput/Singleline/RCTUITextField.m:111]: I think so?
image
```diff
diff --git a/RNTester/js/examples/TextInput/TextInputExample.ios.js b/RNTester/js/examples/TextInput/TextInputExample.ios.js
index f21ca72d3..c8bb90377 100644
--- a/RNTester/js/examples/TextInput/TextInputExample.ios.js
+++ b/RNTester/js/examples/TextInput/TextInputExample.ios.js
@@ -530,6 +530,7 @@ const styles = StyleSheet.create({
     padding: 4,
   },
   multiline: {
+    backgroundColor: '#ff00ff',
     borderWidth: StyleSheet.hairlineWidth,
     borderColor: '#0f0f0f',
     flex: 1,
```
