### PR TITLE
Fix Dimension for macOS

### LINKED ISSUE #326: window/screen Dimensions related issues
I've noticed a few issues regarding accessing global window dimensions:

- [`Dimensions.get('window')`](https://reactnative.dev/docs/dimensions) will always return the screen size (should return the window size)
- [`Dimensions.get('screen')`](https://reactnative.dev/docs/dimensions) will throw an error (key not set)
- [`useWindowDimensions`](https://reactnative.dev/docs/usewindowdimensions) will throw (not defined)

### LINKED ISSUE #334: Skip bundling for macOS platform when in Debug mode
Probably sure it changed with the 0.61.x releases, I noticed unusual long build times while playing with native modules.

I think we should change [this line in react-native-xcode.sh#L35](https://github.com/microsoft/react-native/blob/v0.61.0-microsoft.5/scripts/react-native-xcode.sh#L35) to `if [[ "$PLATFORM_NAME" == *simulator || "$PLATFORM_NAME" == macosx ]]; then` so that bundling is not done when running in debug mode.

Build times (hot cache) went from 5+seconds back to nearly instant.

### PR DESCRIPTION
**Pull request by tom-un**
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native :thumbsup:
- [x] I am making a fix / change for the macOS implementation of react-native
- [ ] I am making a change required for Microsoft usage of react-native

macOS was misbehaving for the Dimensions API.   For `Dimensions.get('screen')` it was never returning anything.   If there was a root view, then `Dimensions.get('window')` was returning the dimension of the root view -- not the window.   If there was no root view, `Dimensions.get('window')` would return the dimensions of the first screen.

**EDIT**: Per the ongoing discussion in Issue #326, and to preserve the existing behavior in RN macOS, I've changed the logic to continue to return rootView dimensions when possible for 'window'.

Now we will always return a value for 'screen' and 'window'.   If there is a root view, it will return the dimensions of its parent window for 'window' and window's screen for 'screen'.   If there is no root view or its not in a window yet, it will fall back to the App's keyWindow.   If there is no keyWindow, it will fall back to the mainScreen.

Closes #326 
Close #334 

#### Focus areas to test

Manually tested the Dimensions page in RNTester and the full test suite.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-macos/pull/348)

### CODE REVIEW

File: scripts/react-native-xcode.sh [hunk 1]
```diff
@@ -32,7 +32,7 @@ fi
 
 case "$CONFIGURATION" in
   *Debug*)
-    if [[ "$PLATFORM_NAME" == *simulator ]]; then
+    if [[ "$PLATFORM_NAME" == *simulator || "$PLATFORM_NAME" == macosx ]]; then
```
Comment (TheSavior) [inline scripts/react-native-xcode.sh:35]: Why does this need to change?

Comment (tom-un) [reply scripts/react-native-xcode.sh:35]: It address Issue #334 and only impacts Debug builds.

File: React/UIUtils/RCTUIUtils.m [hunk 2]
```diff
@@ -72,18 +72,20 @@ RCTDimensions RCTGetDimensions(RCTPlatformView *rootView) {
   };
   NSScreen *screen = nil;
   NSWindow *window = nil;
+  NSSize windowSize;
```
Comment (anandrajeswaran) [inline React/UIUtils/RCTUIUtils.m:75]: Since this is sometimes window size and sometimes not, can we name it something that doesn't suggest it is always the windowSize?

Comment (anandrajeswaran) [reply React/UIUtils/RCTUIUtils.m:75]: maybe even just "size"
