### PR TITLE
Fix `transform` prop on `View` component

### LINKED ISSUE #2038: The transform style does not work in version 0.73.*
### Environment

```markdown
react-native -v: 0.73.2
npm ls react-native-macos: 0.73.6
node -v: 21.4.0
npm -v: 10.2.4
yarn --version: 1.22.19
xcodebuild -version: Xcode 15.0 Build version 15A240d
```

### Steps to reproduce the bug

Adds transform style related properties to the element. 

`<View
              style={{
                width: 50,
                height: 50,
                backgroundColor: 'red',
                opacity: 1,
                transform: [{scaleX: 2}, {translateX: 80}, {rotateX: '45deg'}],
              }}></View>`

### Expected Behavior

Correct rendering of transform style related properties.

### Actual Behavior

截屏2024-01-17 18 14 21

The transform style-related properties are valid on iOS, but not on macOS.

### Reproducible Demo

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by amgleitman**
## Summary:

Fixes #2038.

We believe that the bug was introduced when [this commit](https://github.com/microsoft/react-native-macos/commit/5f40f0800e64b4380d7897b2e8b9ff561d84b97c) was merged in. This commit refactors how the transform prop is handled on the native side, but we didn't properly adapt it for macOS. We do that now.

## Test Plan:

We added a `{skewX: '10deg'}` transform to the "New App Screen Colors" section on the new app screen example in RNTester. The skew now appears correctly as it did under 0.72-stable.

| Before | After |
|-|-|
| Screenshot 2024-03-22 at 4 14 52 PM | Screenshot 2024-03-22 at 4 14 12 PM |

Also verified that animations involving transformations work as well.

### CODE REVIEW

File: packages/react-native/React/Views/UIView+React.m [hunk 1]
```diff
@@ -306,9 +307,16 @@ static void updateTransform(RCTPlatformView *view) // [macOS]
     transform = view.reactTransform;
   }
 
+#if !TARGET_OS_OSX // [macOS]
   view.layer.transform = transform;
   // Enable edge antialiasing in rotation, skew, or perspective transforms
   view.layer.allowsEdgeAntialiasing = transform.m12 != 0.0f || transform.m21 != 0.0f || transform.m34 != 0.0f;
+#else // [macOS
+  if ([view isKindOfClass:[RCTView class]]) {
```
Comment (Saadnajmi) [inline packages/react-native/React/Views/UIView+React.m:315]: Would this get better if this PR ever lands? https://github.com/microsoft/react-native-macos/pull/1936

File: packages/react-native/React/Views/UIView+React.m [hunk 2]
```diff
@@ -12,6 +12,7 @@
 #import "RCTAssert.h"
 #import "RCTLog.h"
 #import "RCTShadowView.h"
+#import "RCTView.h"
```
Comment (Saadnajmi) [inline packages/react-native/React/Views/UIView+React.m:15]: I think this might cause a circular dependency problem. OK since we already have some and don't support the `use_frameworks` option, but might be something we'll want to undo later.

Also, macOS tag

File: packages/react-native/React/Views/UIView+React.m (hunk 1 above)
Comment (Saadnajmi) [reply packages/react-native/React/Views/UIView+React.m:315]: This feels like a code smell to me since we're checking in a base class if we're a specific type of subclass. I almost wonder if it's better to copy the implementation of `setTransform3D` to here, but I think that's what the earlier PR I linked does. It feels like the PR above is the more "correct" solution, but this solution unblocks.

Comment (amgleitman) [reply packages/react-native/React/Views/UIView+React.m:315]: The PR linked doesn't quite do that; it makes `transform3D` a property of `RCTUIView`, not `NSView`. Perhaps the methods that invoke `updateTransform` (all localized to this file) should be under `RCTUIView` as well.

This isn't an issue in RNCore because `RCTUIView` is a construct exclusive to react-native-macos, and it gets `#define`d as `UIView` when react-native-macos gets compiled for iOS.

Comment (Saadnajmi) [reply packages/react-native/React/Views/UIView+React.m:315]: I think moving logic for `updateTransform` to this file makes sense. I'd rather not have the RCTView -> RCTUIView -> UIView+React -> RCTView dependency cycle.

Comment (amgleitman) [reply packages/react-native/React/Views/UIView+React.m]: Moving all the logic from `updateTransform` to `RCTUIView` would require additional work based on its callers, but moving the actual meat of the work into `RCTView` is easy enough, as seen in a4c03ca.

File: packages/react-native/React/Views/RCTView.m [hunk 3]
```diff
@@ -1318,6 +1318,14 @@ - (void)displayLayer:(CALayer *)layer
   [self updateClippingForLayer:layer];
 }
 
+#if TARGET_OS_OSX // [macOS
+- (void)updateInternalReactTransform:(CATransform3D)transform
+{
+  [self setTransform3D:transform];
+  [self setNeedsDisplay];
```
Comment (Saadnajmi) [inline packages/react-native/React/Views/RCTView.m:1325]: Do we need this line? If stuff works without it, I'm not opposed to removing it. Not blocking though.

File: packages/react-native/React/Views/RCTView.m [hunk 4]
```diff
@@ -1318,6 +1318,14 @@ - (void)displayLayer:(CALayer *)layer
   [self updateClippingForLayer:layer];
 }
 
+#if TARGET_OS_OSX // [macOS
+- (void)updateInternalReactTransform:(CATransform3D)transform
```
Comment (Saadnajmi) [inline packages/react-native/React/Views/RCTView.m:1322]: Nit: I think `updateReactTransformInternal` matches convention elsewhere

File: packages/react-native/React/Views/UIView+React.h [hunk 5]
```diff
@@ -83,6 +83,14 @@ typedef struct {
  */
 - (void)reactSetFrame:(CGRect)frame;
 
+
+#if TARGET_OS_OSX // [macOS
+/**
+ * Used by react-native-macos to propagate transform changes internally.
```
Comment (Saadnajmi) [inline packages/react-native/React/Views/UIView+React.h:89]: Maybe just `used on macOS`, since we're in the react-native-macos source? And maybe a small explainer why macOS specifically needs this method while iOS doesn't?

File: packages/react-native/React/Views/UIView+React.m [hunk 6]
```diff
@@ -306,10 +306,21 @@ static void updateTransform(RCTPlatformView *view) // [macOS]
...
   view.layer.allowsEdgeAntialiasing = transform.m12 != 0.0f || transform.m21 != 0.0f || transform.m34 != 0.0f;
+#else // [macOS
+  [view updateInternalReactTransform:transform];
+#endif // macOS]
+}
+
+#if TARGET_OS_OSX // [macOS
+- (void)updateInternalReactTransform:(CATransform3D)transform
+{
+  // Do nothing, this will get overridden by RCTView
```
Comment (Saadnajmi) [inline packages/react-native/React/Views/UIView+React.m:321]: Maybe `RCTView and others`? As in, does `RCTImageView` and the other primitives need to implement this?

**Review by Saadnajmi — APPROVED** [review]
Approved with some nits. mostly on comments and naming

File: packages/react-native/React/Views/RCTView.m (hunk 3 above)
Comment (amgleitman) [reply packages/react-native/React/Views/RCTView.m:1325]: I don't see anything immediately wrong if we remove it, but considering that [it was originally present](https://github.com/microsoft/react-native-macos/blob/80a1f9e7782f9a96c6607460270830a48f28946b/packages/react-native/React/Views/RCTViewManager.m#L250), I'd rather not remove it here.
