### PR TITLE
Fix <Image> tintColor

### LINKED ISSUE #315: [Image] tintColor does not work on macOS
The `tintColor` prop on the Image component does nothing. This can easily be seen in the RNTester image example.

## React Native version:
Cloned master with version 0.60.0-microsoft.75, hash 12f726589daf17b2028b7cdf3519c3ebb5ffc2d9

## Steps To Reproduce

1. Build and run RNTester-macOS
2. Open <Image> example
3. Scroll to 'Tint Color' section

## Describe what you expected to happen:

The 4 thumb icons should have different colors, but they are all gray:

Screen Shot 2020-04-22 at 11 38 04 AM

### PR DESCRIPTION
**Pull request by tom-un**
#### Please select one of the following
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [x] I am making a fix / change for the macOS implementation of react-native
- [ ] I am making a change required for Microsoft usage of react-native

## Summary

The macOS version of `<Image>` never supported the `tintColor` prop.  Since macOS 10.14 there is now NSImageView tint support, so map the react-native prop.

This fix is branched off the https://github.com/microsoft/react-native-macos/pull/407 fix, so i contains all the diffs from that PR as well.   When the 407 PR completes, I'll merge it into this branch.

Fixes #315 

## Changelog

[macOS] [Fixed] - Fix `<Image>` tintColor

## Test Plan

tint

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-macos/pull/408)

### CODE REVIEW

File: Libraries/Image/RCTImageView.h [hunk 1]
```diff
@@ -38,15 +32,6 @@ typedef NS_ENUM(NSInteger, UIImageRenderingMode) {
...
- * macOS Properties
- */
-@property (nonatomic, copy) RCTDirectEventBlock onDoubleClick;
-@property (nonatomic, copy) RCTDirectEventBlock onClick;
-@property (nonatomic, copy) RCTDirectEventBlock onMouseEnter;
-@property (nonatomic, copy) RCTDirectEventBlock onMouseLeave;
-@property (nonatomic, copy) RCTDirectEventBlock onDragEnter;
-@property (nonatomic, copy) RCTDirectEventBlock onDragLeave;
-@property (nonatomic, copy) RCTDirectEventBlock onDrop;
+@property (nonatomic, strong) RCTUIColor *tintColor;
```
Comment (anandrajeswaran) [inline Libraries/Image/RCTImageView.h:35]: Since this is in a TARGET_OS_OSX block, just use NSColor directly?

Comment (anandrajeswaran) [inline Libraries/Image/RCTImageView.h:35]: Are we matching another property with strong? Or should we just be using copy since NSColor conforms to NSCopying

Comment (tom-un) [reply Libraries/Image/RCTImageView.h:35]: good idea.

Comment (tom-un) [reply Libraries/Image/RCTImageView.h:35]: It was mimicking the `tintColor` property of `UIView`, but you're right, it should really be the same as the `contentTintColor` of `NSImageView` and other NSColor properties in AppKit.    Also, RCTImageview doesn't need an ivar, it should just return the underlying NSImageView's contentTintColor.
