### PR TITLE
Fix onSubmitEditing firing on delete/tab

### LINKED ISSUE #429: OnSubmitEditing fires at wrong time on TextInput
### Environment
System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.21 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: 1.22.0 - ~/.volta/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.0
      System Images: android-28 | Google Play Intel x86 Atom, android-R | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

### Issue

When using TextInput field onSubmitEditing is being fired when pressing the backspace key

### Steps to Reproduce

1. Create the following component:

```javascript
<TextInput
        placeholder="+ Add Entry..."
        onSubmitEditing={() => console.warn('onSubmitEditing fired')}
        multiline
        numberOfLines={10}
/>
```

2. Start typing, when you press Cmd+Enter the onSubmitEditing function is called correctly
3. Now press Delete key
4. onSubmitEditing will also fire

### Expected Behavior

expected `onSubmitEditing` to only fire when pressing the Enter key

### PR DESCRIPTION
**Pull request by tido64**
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [x] I am making a fix / change for the macOS implementation of react-native
- [ ] I am making a change required for Microsoft usage of react-native

## Summary

`onSubmitEditing` is fired on delete/tab keys because we check `-[RCTBaseTextInputView textInputShouldReturn]`, which also sends a submit event, too early.

Resolves #429

## Changelog

[macOS] [Fixed] - Fix onSubmitEditing firing on delete/tab

## Test Plan

1. Launch RNTester and go to TextInput screen
2. Filter on "submit"
3. Type something in the multiline TextInput instance and try deleting/tabbing.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-macos/pull/442)

### CODE REVIEW

File: Libraries/Text/TextInput/RCTBackedTextInputDelegateAdapter.m [hunk 1]
```diff
@@ -353,7 +353,7 @@ - (BOOL)textView:(NSTextView *)textView doCommandBySelector:(SEL)commandSelector
   BOOL commandHandled = NO;
   id<RCTBackedTextInputDelegate> textInputDelegate = [_backedTextInputView textInputDelegate];
   // enter/return
-  if (textInputDelegate.textInputShouldReturn && (commandSelector == @selector(insertNewline:) || commandSelector == @selector(insertNewlineIgnoringFieldEditor:))) {
+  if ((commandSelector == @selector(insertNewline:) || commandSelector == @selector(insertNewlineIgnoringFieldEditor:)) && textInputDelegate.textInputShouldReturn) {
```
Comment (tido64) [inline Libraries/Text/TextInput/RCTBackedTextInputDelegateAdapter.m:356]: @tom-un, @shergin, @TheSavior: I don't have the full context on why `textInputShouldReturn` also sends a submit event. Is this something we should fix upstream to avoid future surprises?

File: Libraries/Text/TextInput/RCTBackedTextInputDelegateAdapter.m [hunk 2]
```diff
@@ -352,9 +357,11 @@ - (BOOL)textView:(NSTextView *)textView doCommandBySelector:(SEL)commandSelector
 {
   BOOL commandHandled = NO;
   id<RCTBackedTextInputDelegate> textInputDelegate = [_backedTextInputView textInputDelegate];
-  // enter/return
-  if (textInputDelegate.textInputShouldReturn && (commandSelector == @selector(insertNewline:) || commandSelector == @selector(insertNewlineIgnoringFieldEditor:))) {
-    [_backedTextInputView.window makeFirstResponder:nil];
+  // cmd + enter/return
+  if (commandSelector == @selector(noop:) && RCTEventIsCommandEnterEvent(NSApp.currentEvent)) {
```
Comment (tom-un) [inline Libraries/Text/TextInput/RCTBackedTextInputDelegateAdapter.m:361]: Interesting: the system sends a `noop:` selector on Cmd+Enter?

Comment (tido64) [reply Libraries/Text/TextInput/RCTBackedTextInputDelegateAdapter.m:361]: Yup, that was news to me as well :smile:
