### PR TITLE
Fix exception thrown when unfocusing multiline TextInput

### LINKED ISSUE #432: Multiline textInput throws exception when loosing focus
### Environment

npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.89 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: 1.22.0 - ~/.volta/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.0
      System Images: android-28 | Google Play Intel x86 Atom, android-R | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

### Issue
When using a multiline textInput, when it looses focus it causes a firstResponder resigned exception:

### Steps to Reproduce

1. Create a <TextInput multiline/>
2. Click on it, write something
3. Click outside (or loose focus somehow)
4. Exception will be thrown

### Expected Behavior

No exception thrown when using multiline

Screenshot 2020-06-01 at 10 32 55

### PR DESCRIPTION
**Pull request by tido64**
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [x] I am making a fix / change for the macOS implementation of react-native
- [ ] I am making a change required for Microsoft usage of react-native

## Summary

`-resignFirstResponder` is not supposed to be called directly. See https://developer.apple.com/documentation/appkit/nsresponder/1532115-resignfirstresponder?language=objc

Resolves #432

## Changelog

[macOS] [Fixed] - Exception thrown when unfocusing multiline TextInput

## Test Plan

1. Open RNTester and go to the TextInput screen
2. Find a multi-line TextInput and try focusing/unfocusing it several times

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-macos/pull/441)

### CODE REVIEW

File: React/Views/UIView+React.m [hunk 1]
```diff
@@ -284,7 +284,13 @@ - (void)reactFocusIfNeeded {
 }
 
 - (void)reactBlur {
+#if TARGET_OS_OSX // TODO(macOS ISS#2323203)
+  if (self == self.window.firstResponder) {
```
Comment (tom-un) [inline React/Views/UIView+React.m:288]: nit: even though upstream dot notation is used, we try to avoid dot notation in the mac fork
