### PR TITLE
Fix disable scrolling for multiline text input

### LINKED ISSUE #558: [TextInput] scrollEnabled is not working for the multiline inputs
### Environment

1. `react-native -v`: 0.61.5
3. `npm ls react-native-macos`: 0.61.65
4. `node -v`: 14.7.0
5. `npm -v`: 6.14.4
6. `yarn --version` 1.22.4
7. `xcodebuild -version`: 11E708

### Issue

Refs: https://reactnative.dev/docs/textinput#scrollenabled

Currently when TextInput have `multiline` property and `scrollEnabled` is set to `false` user can still scroll the input content.

Aug-20-2020 22-57-07

### Steps to Reproduce

1. Clone `https://github.com/Simek/react-native-macos-reminders.git`
2. Open `macos/Reminders.xworkspace` in Xcode
3. Build or launch the app
4. Try to scroll when main reminder TextInput is focused

### Expected Behavior

TextInput content do not scroll.

### Actual Behavior

User can scroll the content on multiline TextInput even when `scrollEnabled` is set to `false`.

### Reproducible Demo

* https://github.com/Simek/react-native-macos-reminders

### Additional context

AMA

### PR DESCRIPTION
**Pull request by shwanton**
#### Please select one of the following
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [x] I am making a fix / change for the macOS implementation of react-native
- [ ] I am making a change required for Microsoft usage of react-native

## Summary

RN iOS supports disabling Multiline text input scrolling with `scrollEnabled` prop. https://reactnative.dev/docs/0.68/textinput#scrollenabled-ios

Since macOS does not use `UITextView` which inherits from `UIScrollView`, the `RCTBaseTextInputViewManager` `scrollEnabled` remap was not used.

On macOS, `RCTMultilineTextInputView` creates a `RCTUIScrollView` which is where we need to disable scrolling.
https://github.com/microsoft/react-native-macos/blob/d9bcca937cab7edc00a8115f6883e4497dcd8756/Libraries/Text/TextInput/Multiline/RCTMultilineTextInputView.m#L31

~`RCTUIScrollView` inherits from `NSScrollView` which does not have a `scrollEnabled` property, but there is a [scrollWheel  callback api](https://developer.apple.com/documentation/appkit/nsscrollview/1403494-scrollwheel) we can use to disable scrolling when `scrollEnabled` is `false`.~

**UPDATE:** 

This approach was problematic since overriding `scrollWheel` for all scrollViews caused issues when pasting large amounts of text.
This also did not disable keyboard scrolling with up/down keys.

Another solution is to disable scrolling for TextInput is to [create a custom clipview & constrain scrolling](https://stackoverflow.com/questions/8608572/nsscrollview-disable-autoscrolling).

#1366 added vertical scrollbars to all multiline text inputs. This introduced a layout regression where the scrollbar padding was not taken into account. The scrollbar should also be optional since scrolling can still happen w/o the vertical scrollbar. 

Will add follow on diff to move this to configurable prop.

## Changelog

[macOS] [Fixed] - Scrolling on Multiline Text Input can be disabled
Fixes #558 & #925 

## Usage

NOTE: Only works with `multiline={true}`

```
<TextInput multiline={true} scrollEnabled={false} ... />
```

## Test Plan

Added Example to RNTester TextInput -> Multiline

https://user-images.githubusercontent.com/96719/192339861-fa1faa56-a7e5-4559-a4d1-ea3bffe2ee1d.mp4

### CODE REVIEW

File: Libraries/Text/TextInput/RCTBaseTextInputViewManager.m [hunk 1]
```diff
@@ -52,7 +52,6 @@ @implementation RCTBaseTextInputViewManager
 RCT_REMAP_OSX_VIEW_PROPERTY(spellCheck, backedTextInputView.automaticSpellingCorrectionEnabled, BOOL) // TODO(macOS GH#774)
 RCT_REMAP_NOT_OSX_VIEW_PROPERTY(caretHidden, backedTextInputView.caretHidden, BOOL) // TODO(macOS GH#774)
 RCT_REMAP_NOT_OSX_VIEW_PROPERTY(clearButtonMode, backedTextInputView.clearButtonMode, UITextFieldViewMode) // TODO(macOS GH#774)
-RCT_REMAP_VIEW_PROPERTY(scrollEnabled, backedTextInputView.scrollEnabled, BOOL)
```
Comment (shwanton) [inline Libraries/Text/TextInput/RCTBaseTextInputViewManager.m:55]: `scrollEnabled` is only relevant for multiline input. Moved the remap to `RCTMultilineTextInputViewManager`

**Comment by Saadnajmi** [comment]
@mischreiber Could I get a second pair of eyes on this PR?

**Comment by Saadnajmi** [comment]
And maybe also @chiuam who was looking at TextInput recently

File: Libraries/Text/TextInput/Multiline/RCTMultilineTextInputView.h [hunk 2]
```diff
@@ -11,6 +11,10 @@ NS_ASSUME_NONNULL_BEGIN
 
 @interface RCTMultilineTextInputView : RCTBaseTextInputView
 
+#if TARGET_OS_OSX
+@property (nonatomic, assign) BOOL scrollEnabled;
+#endif
+
```
Comment (Saadnajmi) [inline Libraries/Text/TextInput/Multiline/RCTMultilineTextInputView.h:17]: We mark macOS specific changes with the following tags to make it easy to see where we have introduced diffs with RN Core. Could you add those here as well?
```suggestion
#if TARGET_OS_OSX // [TODO(macOS GH#774)
@property (nonatomic, assign) BOOL scrollEnabled;
#endif // TODO(macOS GH#774)]

```

File: Libraries/Text/TextInput/Multiline/RCTMultilineTextInputView.m [hunk 3]
```diff
@@ -89,6 +89,16 @@ - (void)setReactBorderInsets:(UIEdgeInsets)reactBorderInsets
...
+- (void)setScrollEnabled:(BOOL)scrollEnabled
+{
+  _scrollView.scrollEnabled = scrollEnabled;
+}
+
+- (BOOL)scrollEnabled
+{
+  return _scrollView.isScrollEnabled;
+}
 #endif // ]TODO(macOS GH#774)
```
Comment (Saadnajmi) [inline Libraries/Text/TextInput/Multiline/RCTMultilineTextInputView.m:102]: These shouldn't need a tag, since they're already contained in one.

File: Libraries/Text/TextInput/Multiline/RCTMultilineTextInputViewManager.m [hunk 4]
```diff
@@ -21,5 +21,6 @@ - (RCTUIView *)view // TODO(macOS ISS#3536887)
 
 RCT_REMAP_NOT_OSX_VIEW_PROPERTY(dataDetectorTypes, backedTextInputView.dataDetectorTypes, UIDataDetectorTypes) // TODO(macOS GH#774)
 RCT_REMAP_OSX_VIEW_PROPERTY(dataDetectorTypes, backedTextInputView.enabledTextCheckingTypes, NSTextCheckingTypes) // TODO(macOS GH#774)
+RCT_EXPORT_VIEW_PROPERTY(scrollEnabled, BOOL)
```
Comment (Saadnajmi) [inline Libraries/Text/TextInput/Multiline/RCTMultilineTextInputViewManager.m:24]: I guess this is a macOS specific file is why this macro wasn't already here?

File: Libraries/Text/TextInput/RCTBaseTextInputViewManager.m (hunk 1 above)
Comment (Saadnajmi) [reply Libraries/Text/TextInput/RCTBaseTextInputViewManager.m:55]: Is this a change to the iOS implementation as well? Does that need to be made upstream first or afterwards?

File: packages/rn-tester/js/examples/TextInput/TextInputExample.ios.js [hunk 5]
```diff
@@ -611,6 +611,12 @@ exports.examples = ([
             multiline={true}
             style={styles.multiline}
           />
+          <TextInput
+            placeholder="multiline text input with scroll disabled"
+            multiline={true}
+            scrollEnabled={false}
+            style={styles.multiline}
+          />
```
Comment (Saadnajmi) [inline packages/rn-tester/js/examples/TextInput/TextInputExample.ios.js:619]: Also macOS tags here.

File: React/Base/macOS/RCTUIKit.m [hunk 6]
```diff
@@ -522,6 +531,16 @@ - (void)setAlwaysBounceVertical:(BOOL)alwaysBounceVertical
   self.verticalScrollElasticity = alwaysBounceVertical ? NSScrollElasticityAllowed : NSScrollElasticityNone;
 }
 
+- (void)scrollWheel:(NSEvent *)theEvent
```
[the remark this answers is not in the document]
Comment (mischreiber) [reply React/Base/macOS/RCTUIKit.m:534]: I just checked and iOS does in fact disable keyboard scrolling in that case, so I don't believe this is a complete/sufficient fix.

File: packages/rn-tester/js/examples/TextInput/TextInputExample.ios.js (hunk 5 above)
Comment (lyahdav) [reply packages/rn-tester/js/examples/TextInput/TextInputExample.ios.js:619]: @shwanton seems like this could be upstreamed to RN core if you want.

File: React/Base/macOS/RCTUIKit.m (hunk 6 above)
[the remark this answers is not in the document]
Comment (shwanton) [reply React/Base/macOS/RCTUIKit.m:534]: Confirmed this as well. I'll look into disabling keyboard scrolling.

**Comment by Saadnajmi** [comment]
We're waiting on the "disable keyboard scrolling" bit to move this PR forward.

**Comment by shwanton** [comment]
Quick update. There is a better solution that disables scroll wheel & text that uses a custom clip view.
There is some weird behavior however when I override the clip view so I'm looking to fix that before I update this PR.

**Comment by Saadnajmi** [comment]
> This pull request has been automatically marked as stale because it has been marked as requiring author feedback but has not had any activity for **7 days**. It will be closed if no further activity occurs **within 7 days of this comment**.

Uh... Don't close?

**Comment by shwanton** [comment]
Still working on this fix!

File: React/Base/macOS/RCTUIKit.m (hunk 6 above)
[the remark this answers is not in the document]
Comment (Saadnajmi) [reply React/Base/macOS/RCTUIKit.m:534]: @mischreiber I confirmed that our <ScrollView> currently still scrolls with keyboard events even with `scrollEnabled` set to false.  It looks like in our code, we have the same solution as [here](https://apptyrant.com/2015/05/18/how-to-disable-nsscrollview-scrolling/) to mimic the iOS specific `scrollEnabled` prop, but it doesn't account for keyboard events.

When #1365 lands, we could also override keyDown and just listen for the `PageUp / PageDown` keys for scrolling. I'm not sure if there are more keyboard events that cause scrolling (maybe ArrowUp and ArrowDown inside a TextInput?)

[the remark this answers is not in the document]
Comment (mischreiber) [reply React/Base/macOS/RCTUIKit.m:534]: @Saadnajmi I believe it'll be any key event that moves the insertion point. That includes forward/back, home/end, and possibly others I'm not thinking of.

[the remark this answers is not in the document]
Comment (Saadnajmi) [reply React/Base/macOS/RCTUIKit.m:534]: Gotcha. I missed that @shwanton was working on an alternate fix below too!

**Comment by christophpurrer** [comment]
Will this change now conflict with 
https://github.com/microsoft/react-native-macos/pull/1366 
?

**Comment by shwanton** [comment]
I've updated the description with the latest implementation details for disabling scrolling in multiline textview.
This solution solves the outstanding issues w/ overriding `scrollWheel`

The vertical scrollbar should be optional, I will follow up #1368 with a change we made.


https://user-images.githubusercontent.com/96719/192348760-e86acfaf-9058-49dc-9f84-86978a313912.mp4

**Comment by shwanton** [comment]
@Saadnajmi The updated fix here is ready to be merged!

File: React/Base/macOS/RCTUIKit.m (hunk 6 above)
[the remark this answers is not in the document]
Comment (chiuam) [reply React/Base/macOS/RCTUIKit.m]: Resolving as the updated fix no longer overrides `scrollWheel`

File: Libraries/Text/TextInput/Multiline/RCTMultilineTextInputViewManager.m (hunk 4 above)
Comment (chiuam) [reply Libraries/Text/TextInput/Multiline/RCTMultilineTextInputViewManager.m:27]: I think is a shared file by looking at macros like `RCT_REMAP_NOT_OSX_VIEW_PROPERTY` and `RCT_REMAP_OSX_VIEW_PROPERTY `

**Review by chiuam — APPROVED** [review]
