### PR TITLE
Fix bugs with multiline TextInput

### LINKED ISSUE #611: Multiline TextInput with attributed text is rendered vertically offset
### Issue

If a TextInput component is multiline and has text attributes (font styles) the text can be rendered vertically offset from the components bounds.

### Steps to Reproduce

1. Run RNTester and navigate to the TextInput test page
2. Scroll down to the Multiline section
3. Notice that the red "multiline textinput with font styles and placeholder" is rendered *below* the second TextInput rectangle
4. Click in the second TextInput and type.
5. Notice that whatever you type is rendering below and outside of the second TextInput rectangle.

### Expected Behavior

The TextInput's text should render within the bounds of the TextInput component.

### Actual Behavior

The TextInput's text is offset vertically and is rendering outside of the TextInput bounds.

ezgif com-gif-maker

### Additional context

This is not a new issue.   TextInput that is multiline and has font styling has always had this issue in react-native-macos.   Its unclear what the root cause issue may be -- maybe something to do with macOS NSView's default coordinate system being flipped vertically unlike iOS UIViews.

### LINKED ISSUE #639: Multiline TextInput scrolls to top when inserting newline at bottom when it has more content than fits in view
### Environment

(Not filling this out because I'm submitting PR for fix soon, but I'm on master as of now)

### Issue

See title

### Steps to Reproduce

1. Open RNTester > TextInput > Multiline
2. Enter a bunch of newlines

### Expected Behavior

When TextInput starts scrolling, it keeps scroll position where cursor is.

### Actual Behavior

Scrolls to top.

### PR DESCRIPTION
**Pull request by lyahdav**
fixes #639
fixes #611

# :warning: Make sure you are targeting microsoft/react-native-macos for your PR :warning:
(then delete these lines)

#### Please select one of the following
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [x] I am making a fix / change for the macOS implementation of react-native
- [ ] I am making a change required for Microsoft usage of react-native

## Summary

fixes #639
fixes #611

## Changelog

[macOS] [Fixed] - Fixed bugs #639 and #611 with multiline TextInput

## Test Plan

Verify in RNTester > TextInput > Multiline these bugs are fixed.
image

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-macos/pull/640)

### CODE REVIEW

File: Libraries/Text/TextInput/Multiline/RCTUITextView.m [hunk 1]
```diff
@@ -56,7 +56,14 @@ - (instancetype)initWithFrame:(CGRect)frame
     self.backgroundColor = [RCTUIColor clearColor]; // TODO(macOS ISS#2323203)
     self.textColor = [RCTUIColor blackColor]; // TODO(macOS ISS#2323203)
     // This line actually removes 5pt (default value) left and right padding in UITextView.
+#if !TARGET_OS_OSX // TODO(macOS ISS#2323203)
     self.textContainer.lineFragmentPadding = 0;
+#else
+    // macOS has a bug where setting this to 0 will cause the scroll view to scroll to top when
+    // inserting a newline at the bottom of a NSTextView when it has more rows than can be displayed
+    // on screen.
```
Comment (alloy) [inline Libraries/Text/TextInput/Multiline/RCTUITextView.m:64]: Is there a radar filed for this and/or another existing public write-up on the bug? If so, can you leave a comment here linking to it?

File: Libraries/Text/TextInput/Multiline/RCTMultilineTextInputView.m [hunk 2]
```diff
@@ -86,7 +86,7 @@ - (void)setReactBorderInsets:(UIEdgeInsets)reactBorderInsets
 {
   [super setReactBorderInsets:reactBorderInsets];
   // We apply `borderInsets` as `_scrollView` layout offset on mac.
-  _scrollView.frame = UIEdgeInsetsInsetRect(self.frame, reactBorderInsets);
+  _scrollView.frame = UIEdgeInsetsInsetRect(self.bounds, reactBorderInsets);
```
Comment (alloy) [inline Libraries/Text/TextInput/Multiline/RCTMultilineTextInputView.m:89]: Classic 👍

**Review by alloy — APPROVED** [review]
Verified these locally 👍 

Thanks!

File: Libraries/Text/TextInput/Multiline/RCTUITextView.m (hunk 1 above)
Comment (lyahdav) [reply Libraries/Text/TextInput/Multiline/RCTUITextView.m:64]: I didn't file a Radar. I'll add it my to todo list, but it's not a high priority now.

**Comment by alloy** [comment]
:shipit:
