### PR TITLE
Fix RCTScrollContentView layout with fixed size

### LINKED ISSUE #363: ScrollView contents not laying out correctly when scroll indicators are always on and ScrollView is fixed width/height
Typically macOS scroll indicators only appear on top of the contents when scrolling using a trackpad or Magic Mouse gesture -- similar to iOS.   But if a PC mouse is attached or the System Preferences are set to show scroll indicators always, then the layout of the ScrollView contents should adjust to the narrower view port.   Currently they are not which can force the appearance of a horizontal scrollbar.

For example, if the following is rendered with many <Text> children
```jsx
    return (
      <ScrollView
        style={{
          flex: 1,
          backgroundColor: 'red',
          width: 200,
          height: 200,
        }}
        contentContainerStyle={{
          flexGrow: 1,
        }}
      >
        <Text>Some text</Text>
        . . . many more . . .
      </ScrollView>
    );
```
and scroll indicators are always on, then the layout of the content view is too wide forcing the appearance of a horizontal scrollbar:

scrolling

UPDATED: A related issue was fixed with the change https://github.com/microsoft/react-native-macos/commit/d604a2d9e2adcdd13391f3487cffa14988c12e2b#diff-f4440252d71357db0518df7c857743f5 in `RCTScrollContentView.m`.   It fixes layout if the ScrollView has variable width/height such as the main screen in RNTester.   But it doesn't work if the ScrollView layout is fixed.    A workaround is to simply wrap the ScrollView in a View and put the fixed constraints on the View:

```jsx
    return (
      <View
        style={{
          flex: 1,
          backgroundColor: 'red',
          width: 200,
          height: 200,
        }}>
        <ScrollView
          contentContainerStyle={{
            flexGrow: 1,
          }}>
          <Text>Some text</Text>
          . . . many more . . .
        </ScrollView>
      </View>
    );
```

### PR DESCRIPTION
**Pull request by tido64**
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [x] I am making a fix / change for the macOS implementation of react-native
- [ ] I am making a change required for Microsoft usage of react-native

## Summary

Always show the vertical scroll bar when **Show scroll bars** is set to **Always**. This makes it consistent with other system apps, such as Finder or Xcode.

Resolves #363

## Changelog

[macOS] [Fixed] - Fix RCTScrollContentView layout with fixed size

## Test Plan

| Before | After |
| :-: | :-: |
| image | image |
| image  | image |

For reference, here's Xcode with **Show scroll bars** set to **Always**:

image

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-macos/pull/453)

### CODE REVIEW

File: React/Views/ScrollView/RCTScrollView.m [hunk 1]
```diff
@@ -185,9 +185,7 @@ - (instancetype)initWithFrame:(CGRect)frame
   if ((self = [super initWithFrame:frame])) {
 #if TARGET_OS_OSX // [TODO(macOS ISS#2323203)
     self.scrollEnabled = YES;
-    self.hasHorizontalScroller = YES;
     self.hasVerticalScroller = YES;
```
Comment (tom-un) [inline React/Views/ScrollView/RCTScrollView.m:188]: I think we need a similar affordance for when the ScrollView is `horizontal={true}`.   I tried ScrollViewExample and its horizontal tests have what looks like a similar problem to the `horizontal={false}` but on the other axis:

horizontal

Does it just need to not call `hasVerticalScroller` here and set it conditionally down on line 754 like it is for `setHasHorizontalScroller` ?

Comment (tido64) [reply React/Views/ScrollView/RCTScrollView.m:189]: Almost:
image
The problem is that we don't regain the area and the view appears clipped. This has always been there but it's more obvious with no vertical scroller. :disappointed:

Comment (tom-un) [reply React/Views/ScrollView/RCTScrollView.m:189]: I checked it out and it so close!    From experimentation, it seems like its the `  [[self scrollView] setHasVerticalScroller:!isHorizontal || scrollsVertically];` call on line 757.   In the `horizontal={true}` case, the `scrollsVertically` is true which it should not?   If I simply omit the ` || scrollsVertically` it seems to work

Comment (tom-un) [reply React/Views/ScrollView/RCTScrollView.m:189]: I found another problem with both horizontal and vertical.   When vertical, the layout height of the content can be cut off:

vertical

I think we need to calculate the need for vertical independent of horizontal (instead of !horizontal).   I tried making a `isVertical:` method parallel to the exisitng `isHorizontal:`.   I changed:
```objc
#if TARGET_OS_OSX // [TODO(macOS ISS#2323203)
  BOOL isHorizontal = [self isHorizontal:_scrollView];
  [[self scrollView] setHasHorizontalScroller:isHorizontal];
  BOOL isVertical = [self isVertical:_scrollView];
  [[self scrollView] setHasVerticalScroller:isVertical];
#endif // ]TODO(macOS ISS#2323203)
```

and in `RCTScrollContentView.m` i changed to:
```objc
      Class horizontalScrollerClass = [scrollView isHorizontal:platformScrollView]
        ? [[platformScrollView horizontalScroller] class]
        : nil;
      Class verticalScrollerClass = [scrollView isVertical:platformScrollView]
        ? [[platformScrollView verticalScroller] class]
        : nil;
```

It's almost there.   The remaining issue is that in a `horizontal={true}` ScrollView, it still scrolls vertically, but without a visible scrollbar.   I can't figure out why:

vertical-scroll

Comment (tido64) [reply React/Views/ScrollView/RCTScrollView.m:189]: I played around with the view hierarchy debugger in Xcode and it looks like only `RCTScrollContentView` is resized. Its subviews are not. That got me thinking that we should probably fix this at the shadow layer, so I hacked together a thing just to confirm:

image

Subviews are correctly resized and no longer clipped (green), but there are a couple of issues with background colors bleeding out (red). And since the shadow view doesn't have a reference to the real view, it doesn't know which scroller is currently visible. I'll continue looking for the correct place to make these adjustments but if you know exactly where to look, please let me know as I'm on unknown territory.

For reference, this is what I did:

```diff
diff --git a/React/Views/RCTShadowView.m b/React/Views/RCTShadowView.m
index ef74f2880..b8b2a0458 100644
--- a/React/Views/RCTShadowView.m
+++ b/React/Views/RCTShadowView.m
@@ -318,6 +318,12 @@ static void RCTProcessMetaPropsBorder(const YGValue metaProps[META_PROP_COUNT],
 }
 
 - (void)layoutSubviewsWithContext:(RCTLayoutContext)layoutContext
+{
+  [self layoutSubviewsWithContext:layoutContext adjustForLegacyScrollers:NO];
+}
+
+- (void)layoutSubviewsWithContext:(RCTLayoutContext)layoutContext
+         adjustForLegacyScrollers:(BOOL)adjustForLegacyScrollers
 {
   RCTLayoutMetrics layoutMetrics = self.layoutMetrics;
 
@@ -338,6 +344,23 @@ static void RCTProcessMetaPropsBorder(const YGValue metaProps[META_PROP_COUNT],
 
     RCTLayoutMetrics childLayoutMetrics = RCTLayoutMetricsFromYogaNode(childYogaNode);
 
+    if (adjustForLegacyScrollers) {
+      childLayoutMetrics.contentFrame.size =
+        [NSScrollView contentSizeForFrameSize:childLayoutMetrics.contentFrame.size
+                      horizontalScrollerClass:[NSScroller class]
+                        verticalScrollerClass:[NSScroller class]
+                                   borderType:NSNoBorder
+                                  controlSize:NSControlSizeRegular
+                                scrollerStyle:NSScrollerStyleLegacy];
+      childLayoutMetrics.frame.size =
+        [NSScrollView contentSizeForFrameSize:childLayoutMetrics.frame.size
+                      horizontalScrollerClass:[NSScroller class]
+                        verticalScrollerClass:[NSScroller class]
+                                   borderType:NSNoBorder
+                                  controlSize:NSControlSizeRegular
+                                scrollerStyle:NSScrollerStyleLegacy];
+    }
+
     layoutContext.absolutePosition.x += childLayoutMetrics.frame.origin.x;
     layoutContext.absolutePosition.y += childLayoutMetrics.frame.origin.y;
 
diff --git a/React/Views/ScrollView/RCTScrollContentShadowView.m b/React/Views/ScrollView/RCTScrollContentShadowView.m
index 16bf6147c..5bc3c06ae 100644
--- a/React/Views/ScrollView/RCTScrollContentShadowView.m
+++ b/React/Views/ScrollView/RCTScrollContentShadowView.m
@@ -11,11 +11,33 @@
 
 #import "RCTUtils.h"
 
+@interface RCTShadowView (RCTScrollContentShadowViewPrivate)
+- (void)layoutSubviewsWithContext:(RCTLayoutContext)layoutContext
+         adjustForLegacyScrollers:(BOOL)adjustForLegacyScrollers;
+@end
+
 @implementation RCTScrollContentShadowView
 
 - (void)layoutWithMetrics:(RCTLayoutMetrics)layoutMetrics
             layoutContext:(RCTLayoutContext)layoutContext
 {
+  if ([NSScroller preferredScrollerStyle] == NSScrollerStyleLegacy) {
+    layoutMetrics.contentFrame.size =
+      [NSScrollView contentSizeForFrameSize:layoutMetrics.contentFrame.size
+                    horizontalScrollerClass:[NSScroller class]
+                      verticalScrollerClass:[NSScroller class]
+                                 borderType:NSNoBorder
+                                controlSize:NSControlSizeRegular
+                              scrollerStyle:NSScrollerStyleLegacy];
+    layoutMetrics.frame.size =
+      [NSScrollView contentSizeForFrameSize:layoutMetrics.frame.size
+                    horizontalScrollerClass:[NSScroller class]
+                      verticalScrollerClass:[NSScroller class]
+                                 borderType:NSNoBorder
+                                controlSize:NSControlSizeRegular
+                              scrollerStyle:NSScrollerStyleLegacy];
+  }
+
   if (layoutMetrics.layoutDirection == UIUserInterfaceLayoutDirectionRightToLeft) {
     // Motivation:
     // Yoga place `contentView` on the right side of `scrollView` when RTL layout is enforced.
@@ -29,4 +51,10 @@
   [super layoutWithMetrics:layoutMetrics layoutContext:layoutContext];
 }
 
+- (void)layoutSubviewsWithContext:(RCTLayoutContext)layoutContext
+{
+  [self layoutSubviewsWithContext:layoutContext
+         adjustForLegacyScrollers:[NSScroller preferredScrollerStyle] == NSScrollerStyleLegacy];
+}
+
 @end
diff --git a/React/Views/ScrollView/RCTScrollContentView.m b/React/Views/ScrollView/RCTScrollContentView.m
index e0e8d5311..9f4bfd793 100644
--- a/React/Views/ScrollView/RCTScrollContentView.m
+++ b/React/Views/ScrollView/RCTScrollContentView.m
@@ -21,25 +21,6 @@
 #else // [TODO(macOS ISS#2323203)
   // macOS also has a NSClipView in its hierarchy
   RCTScrollView *scrollView = (RCTScrollView *)self.superview.superview.superview;
-
-  if (scrollView != nil) {
-    // On macOS scroll indicators may float over the content view like they do in iOS
-    // or depending on system preferences they may be outside of the content view
-    // which means the clip view will be smaller than the scroll view itself.
-    // In such cases the content view layout must shrink accordingly otherwise
-    // the contents will overflow causing the scroll indicators to appear unnecessarily.
-    NSScrollView *platformScrollView = scrollView.scrollView;
-    if (platformScrollView.scrollerStyle == NSScrollerStyleLegacy) {
-      NSScroller *verticalScroller = platformScrollView.verticalScroller;
-      if (!verticalScroller.isHidden) {
-        frame.size.width -= verticalScroller.frame.size.width;
-      }
-      NSScroller *horizontalScroller = platformScrollView.horizontalScroller;
-      if (!horizontalScroller.isHidden) {
-        frame.size.height -= horizontalScroller.frame.size.height;
-      }
-    }
-  }
 #endif // ]TODO(macOS ISS#2323203)
 
   [super reactSetFrame:frame];
diff --git a/React/Views/ScrollView/RCTScrollView.m b/React/Views/ScrollView/RCTScrollView.m
index ad69c86e1..74d623436 100644
--- a/React/Views/ScrollView/RCTScrollView.m
+++ b/React/Views/ScrollView/RCTScrollView.m
@@ -187,7 +187,6 @@ RCT_NOT_IMPLEMENTED(- (instancetype)init)
     self.scrollEnabled = YES;
     self.hasHorizontalScroller = YES;
     self.hasVerticalScroller = YES;
-    self.autohidesScrollers = YES;
     self.panGestureRecognizer = [[NSPanGestureRecognizer alloc] initWithTarget:self action:@selector(handleCustomPan:)];
 #else // ]TODO(macOS ISS#2323203)
     [self.panGestureRecognizer addTarget:self action:@selector(handleCustomPan:)];
@@ -751,6 +750,11 @@ static inline void RCTApplyTransformationAccordingLayoutDirection(RCTPlatformVie
     [self react_updateClippedSubviewsWithClipRect:clipRect relativeToView:clipView];
     _lastClippedToRect = bounds;
   }
+
+#if TARGET_OS_OSX // [TODO(macOS ISS#2323203)
+  [[self scrollView] setHasHorizontalScroller:[self isHorizontal:_scrollView] || scrollsHorizontally];
+  [[self scrollView] setHasVerticalScroller:[self isVertical:_scrollView] || scrollsVertically];
+#endif // ]TODO(macOS ISS#2323203)
 }
 
 #if TARGET_OS_OSX // [TODO(macOS ISS#2323203)
```

Comment (tido64) [reply React/Views/ScrollView/RCTScrollView.m:189]: Latest iteration with local data for `RCTScrollContentShadowView`:
image

File: React/Views/ScrollView/RCTScrollContentShadowView.m [hunk 2]
```diff
@@ -9,10 +9,30 @@
...
+#if TARGET_OS_OSX // [TODO(macOS ISS#2323203)
+- (void)setLocalData:(RCTScrollContentLocalData *)localData
+{
+  RCTAssert(
+      [localData isKindOfClass:[RCTScrollContentLocalData class]],
+      @"Local data object for `RCTScrollContentView` must be `RCTScrollContentLocalData` instance.");
+
+  UIEdgeInsets insets = localData.insets;
+
+  super.marginRight = (YGValue){insets.right, YGUnitPoint};
```
Comment (tom-un) [inline React/Views/ScrollView/RCTScrollContentShadowView.m:29]: This fix is brilliant!  I tested it locally and everything looks perfect.   The only nit I have is to be left-to-right and right-to-left agnostic and use `marginEnd` here instead of `marginRight`.   I tested it in RTL mode, and it still works with `marginRight`, but I still think it would be more semantically correct to use `marginEnd`.

Also, it's not necessary to use a `UIEdgeInsets` on the local data since we only need two `CGFloat` values for `marginEnd` and `marginBottom`.   Recommend change the `RCTScrollContentLocalData` to just have two `CGFloat` type props.

rtl

Comment (tido64) [reply React/Views/ScrollView/RCTScrollContentShadowView.m]: There's still a bug here that I haven't figured out yet. When RNTester starts, trying to grab the vertical scroll indicator also triggers a click on the element under it.
