### PR TITLE
Fix ActivityIndicator with custom color causing brief flicker

### LINKED ISSUE #412: ActivityIndicator causes brief flicker
Reported by @Simek: 

> There is an issue with ActivityIndicator view Example, I assume it's related to the componentDidMount or timer there, for a brief moment just after click (after navigate), the app background became transparent and flickers (maybe it's resized to 0,0 for a ms?), most of other Examples seems to load fine.

ezgif com-video-to-gif

### PR DESCRIPTION
**Pull request by tido64**
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [x] I am making a fix / change for the macOS implementation of react-native
- [ ] I am making a change required for Microsoft usage of react-native

## Summary

The window flickers when rendering a view with an `ActivityIndicator` and a custom colour. This is caused by setting `-[NSView setContentFilters:]`.

Resolves #412

## Changelog

[macOS] [Fixed] - Fix ActivityIndicator with custom color causing brief flicker

## Test Plan

indicator-flicker

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-macos/pull/446)

### CODE REVIEW

File: React/Views/RCTActivityIndicatorView.m [hunk 1]
```diff
@@ -66,33 +69,32 @@ - (void)setActivityIndicatorViewStyle:(UIActivityIndicatorViewStyle)activityIndi
   }
 }
 
-- (void)setColor: (RCTUIColor*)color
+- (void)setColor:(RCTUIColor*)color
 {
   if (_color != color) {
+    if (color != nil) {
+      CGFloat r, g, b, a;
+      [[color colorUsingColorSpaceName:NSCalibratedRGBColorSpace] getRed:&r green:&g blue:&b alpha:&a];
```
Comment (anandrajeswaran) [inline React/Views/RCTActivityIndicatorView.m:77]: Isn't the color we get back not trustable anymore since it moved from updateLayer to setColor: which may not be part of the draw callback? See "Update Custom Views using Specific Methods" at https://developer.apple.com/documentation/xcode/supporting_dark_mode_in_your_interface

Comment (tido64) [reply React/Views/RCTActivityIndicatorView.m]: You're right. I just thought I was being smart by not creating the filter every frame :smile:
