### PR TITLE
Fix multiline TextInput crash when inserting/removing lots of text

### LINKED ISSUE #486: Multiline TextInput crashes after buffer has a certain number of characters and they are deleted
### Environment

"react-native-macos": "^0.61.54"

### Steps to Reproduce
 on a `<TextInput multiline />` try to write several characters (number seems to ~100 - ~300) after you have enough characters in the buffer, try to delete a few of them, react-native will crash:

Screenshot 2020-06-30 at 19 16 36

Screenshot 2020-07-06 at 16 19 58

The problem was happening a lot more often with an older version, now it doesn't happen as often, but still occurs every once in a while, it might take a lot of typing/deleting to reproduce the problem

### PR DESCRIPTION
**Pull request by tido64**
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [x] I am making a fix / change for the macOS implementation of react-native
- [ ] I am making a change required for Microsoft usage of react-native

## Summary

It seems that the returned string that we use to set `previousText` can be mutated while it is waiting to be processed by `RCTBridge `.

Resolves #486

## Changelog

[macOS] [Fixed] - Fix multiline `TextInput` crash when inserting/removing lots of text

## Test Plan

Here's a screenshot showing that the length of `previousText` (`0x600000d952c0`) was 29483 when first accessed, but is 0 when the exception is thrown.

image

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-macos/pull/489)

### CODE REVIEW

File: Libraries/Text/TextInput/RCTBaseTextInputView.m [hunk 1]
```diff
@@ -475,7 +475,7 @@ - (BOOL)textInputShouldChangeTextInRange:(NSRange)range replacementText:(NSStrin
     }
   }
 
-  NSString *previousText = backedTextInputView.attributedText.string ?: @"";
+  NSString *previousText = [backedTextInputView.attributedText.string copy] ?: @""; // TODO(OSS Candidate ISS#2710739)
```
Comment (tom-un) [inline Libraries/Text/TextInput/RCTBaseTextInputView.m:478]: Great find!

The `-[NSAttributedString string]` property is marked `readonly, copy` but it appears that Apple deliberately ignores it per their documentation: https://developer.apple.com/documentation/foundation/nsattributedstring/1412616-string?language=objc

> For performance reasons, this property returns the current backing store of the attributed string object. If you want to maintain a snapshot of this as you manipulate the returned string, you should make a copy of the appropriate substring

Since this string is being processed by the background JS thread it is in danger of being mutated by the foreground thread.   In this case, based on your XCode screenshot, it's crashing in `convertIdToFollyDynamic` presumably when it calls `     NSData *data = [json dataUsingEncoding:NSUTF8StringEncoding];`.   So the background thread is encoding a string and the foreground thread changes it before it completes.

We should do the same manual `copy` on all the places where the string is being passed to the JS thread.   I just audited the source and found these places were we should also be copying the `attributedText.string` before queuing it to the JS thread:
`textInputDidBeginEditing`
`textInputDidEndEditing`
`textInputShouldReturn`
`textInputDidChange`

And the same fix should be contributed upstream.

Comment (tom-un) [reply Libraries/Text/TextInput/RCTBaseTextInputView.m:478]: Also, minor nit: we should either use all dot notation, or all conventional notation.   for the macOS changes we prefer conventional notation, but upstream uses mostly dot notation.   If this goes upstream, they may prefer all dot notation.

Comment (tido64) [reply Libraries/Text/TextInput/RCTBaseTextInputView.m:478]: Regarding the nit: I'm under the impression that the dot notation is only used for properties. Since `copy` is a function, I think it's correct to the use conventional notation here.

Comment (tom-un) [reply Libraries/Text/TextInput/RCTBaseTextInputView.m:478]: Of course.   One of the reasons I hate dot notation.  I confuses me 🤪

Comment (tido64) [reply Libraries/Text/TextInput/RCTBaseTextInputView.m:478]: Upstream: https://github.com/facebook/react-native/pull/29307
