### PR TITLE
fix: add RCTAppDependencyProvider to template

### LINKED ISSUE #2558: Fabric views not registered due to AppDelegate.mm missing dependencyProvider
### Environment

```markdown
npm ls react-native-macos: 0.78.3
node -v: v21.2.0
npm -v: 10.2.3
xcodebuild -version: Xcode 16.4 Build version 16F6
```

### Steps to reproduce the bug

1. Create a new react-native-macos app with the standard steps.
2. Enable the new architecture
3. Create a Fabric component
4. It will render a `RCTUnimplementedViewComponentView`

### Expected Behavior

Should see your custom Fabric view.

### Actual Behavior

_No response_

### Reproducible Demo

_No response_

### Additional context

Should be able to fix by updating the AppDelegate.mm with these lines of code (similar to [RNTester](https://github.com/facebook/react-native/blob/21cd09d4c0fc7622ecf0247d4c4f1251dc06c154/packages/rn-tester/RNTester/AppDelegate.mm#L25-L44)):

```diff
#import "AppDelegate.h"
#import <React/RCTBundleURLProvider.h>

+ #if __has_include(<ReactAppDependencyProvider/RCTAppDependencyProvider.h>)
+ #define USE_OSS_CODEGEN 1
+ #import <ReactAppDependencyProvider/RCTAppDependencyProvider.h>
+ #else
+ #define USE_OSS_CODEGEN 0
+ #endif

@implementation AppDelegate

- (void)applicationDidFinishLaunching:(NSNotification *)notification
{
  // ...

+  // Enable Fabric views
+ #if USE_OSS_CODEGEN
+   self.dependencyProvider = [RCTAppDependencyProvider new];
+ #endif

  return [super applicationDidFinishLaunching:notification];
}
```

### PR DESCRIPTION
**Pull request by Saadnajmi**
## Summary:

Fixes #2558 

This was missing from our template, which meant 3rd party fabric components would not get registered

## Test Plan:

Working on it...

### CODE REVIEW

File: packages/react-native/local-cli/generator-macos/templates/macos/HelloWorld-macOS/AppDelegate.mm [hunk 1]
```diff
@@ -1,6 +1,7 @@
 #import "AppDelegate.h"
 
 #import <React/RCTBundleURLProvider.h>
+#import <ReactAppDependencyProvider/RCTAppDependencyProvider.h>
```
Comment (jamonholmgren) [inline packages/react-native/local-cli/generator-macos/templates/macos/HelloWorld-macOS/AppDelegate.mm:4]: If you're not using codegen, will this exist?

You can use the diff I provided in #2558 if you want to be careful.

**Review by jamonholmgren — APPROVED** [review]
Up to you whether you want to add the file existence check in my diff. Otherwise this should work.

File: packages/react-native/local-cli/generator-macos/templates/macos/HelloWorld-macOS/AppDelegate.mm (hunk 1 above)
Comment (Saadnajmi) [reply packages/react-native/local-cli/generator-macos/templates/macos/HelloWorld-macOS/AppDelegate.mm:4]: Good catch.. I guess CI will tell me if paper fails :D

Comment (Saadnajmi) [reply packages/react-native/local-cli/generator-macos/templates/macos/HelloWorld-macOS/AppDelegate.mm:4]: I think we don't need the existence checks. Those I think are mostly only for RNTester where it is also tested by Meta's internal codebase / build system and not just cocoapods

**Review by tido64 — APPROVED** [review]
